<a href="https://colab.research.google.com/github/chae52/MachineLearning/blob/main/%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5_4%EC%A3%BC%EC%B0%A8_LogisticRegression_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#IRIS

##Data load

In [62]:
import seaborn as sns
iris=sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [63]:
iris_x=iris.drop('species',axis=1)
iris_y=iris['species']

In [64]:
from sklearn.preprocessing import LabelEncoder
classle=LabelEncoder()
iris_y=classle.fit_transform(iris['species'].values)

import numpy as np
print('species : ', np.unique(iris_y))

species :  [0 1 2]


In [65]:
from sklearn.model_selection import train_test_split
print(iris_x.shape,iris_y.shape)

iris_x_train, iris_x_test, iris_y_train, iris_y_test=train_test_split(iris_x,iris_y,test_size=0.3, random_state=1,stratify=y)

(150, 4) (150,)


##표준화

In [66]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(iris_x_train)
iris_x_train_std=sc.transform(iris_x_train)
iris_x_test_std=sc.transform(iris_x_test)

##학습

In [67]:
from sklearn.linear_model import LogisticRegression
#c=1/람다 
logit=LogisticRegression(C=200,random_state=11)
l_1=logit.fit(iris_x_train_std,iris_y_train)
iris_y_train_pred=logit.predict(iris_x_train_std)
iris_y_test_pred=logit.predict(iris_x_test_std)

##평가

In [68]:
from sklearn.metrics import accuracy_score
print(accuracy_score(iris_y_train,iris_y_train_pred))
print(accuracy_score(iris_y_test,iris_y_test_pred))

0.9809523809523809
1.0


In [69]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(iris_y_test,iris_y_test_pred))

[[15  0  0]
 [ 0 15  0]
 [ 0  0 15]]


#Regularization(규제화)

In [105]:
import pandas as pd
import numpy as np

##Wine data load

In [106]:
data_wine=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/'
                     'wine/wine.data',header=None)
data_wine.head()

0      1     2     3     4    5   ...    8     9     10    11    12    13
0   1  14.23  1.71  2.43  15.6  127  ...  0.28  2.29  5.64  1.04  3.92  1065
1   1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28  4.38  1.05  3.40  1050
2   1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81  5.68  1.03  3.17  1185
3   1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18  7.80  0.86  3.45  1480
4   1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82  4.32  1.04  2.93   735

[5 rows x 14 columns]

In [107]:
#열 이름 지정
data_wine.columns=['class label', 'alchohol', 'malic acid', 'ash', 
                    'alcalinity of ash', 'magnesium', 'total phenols', 
                    'flavanoids', 'nonflavanoid phenols', 
                    'proanthocyanins', 'color intensity', 'hue', 
                    'OD208', 'proline'] 
print('class label:', np.unique(data_wine['class label']))
data_wine.head()

class label: [1 2 3]


class label  alchohol  malic acid  ...   hue  OD208  proline
0            1     14.23        1.71  ...  1.04   3.92     1065
1            1     13.20        1.78  ...  1.05   3.40     1050
2            1     13.16        2.36  ...  1.03   3.17     1185
3            1     14.37        1.95  ...  0.86   3.45     1480
4            1     13.24        2.59  ...  1.04   2.93      735

[5 rows x 14 columns]

In [108]:
from sklearn.model_selection import train_test_split
x,y = data_wine.iloc[:,1:].values, data_wine.iloc[:,0].values
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.3 ,random_state=1, stratify=y)

##표준화

In [109]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()

#x_train에 fit된 기준을 x_test에도 똑같이 맞춤(동일한 기준)
x_train_std=std.fit_transform(x_train)
x_test_std=std.transform(x_test)

##L1&L2 Regularization

In [110]:
from sklearn.linear_model import LogisticRegression
lr1_10=LogisticRegression(penalty='l1', C=10.0, solver='saga')# L1 with C(=1/λ)=10
lr1_1=LogisticRegression(penalty='l1', C=1.0, solver='saga')
lr1_0_1=LogisticRegression(penalty='l1', C=0.1, solver='saga')

lr2_10=LogisticRegression(penalty='l2', C=10.0, solver='saga')
lr2_1=LogisticRegression(penalty='l2', C=1.0, solver='saga')
lr2_0_1=LogisticRegression(penalty='l2', C=0.1, solver='saga')

In [111]:
#.score 대신 accuracy_score을 사용해도 됨

print('L1★★★★★★★★')
lr1_10.fit(x_train_std,y_train)
print('Trainng accuracy with L1 and λ=0.1 : ', lr1_10.score(x_train_std,y_train))
print('Test accuracy with L1 and λ=0.1 : ', lr1_10.score(x_test_std, y_test))

lr1_1.fit(x_train_std,y_train)
print('Trainng accuracy with L1 and λ=1 : ', lr1_1.score(x_train_std,y_train))
print('Test accuracy with L1 and λ=1 : ', lr1_1.score(x_test_std, y_test))

lr1_0_1.fit(x_train_std,y_train)
print('Trainng accuracy with L1 and λ=10 : ', lr1_0_1.score(x_train_std,y_train))
print('Test accuracy with L1 and λ=10 : ', lr1_0_1.score(x_test_std, y_test))

print('L2★★★★★★★★')
lr2_10.fit(x_train_std,y_train)
print('Train accuracy with L2 and λ=0.1', lr2_10.score(x_train_std,y_train))
print('Test accuracy with L2 and λ=0.1', lr2_10.score(x_test_std,y_test))

lr2_1.fit(x_train_std,y_train)
print('Train accuracy with L2 and λ=1', lr2_1.score(x_train_std,y_train))
print('Test accuracy with L2 and λ=1', lr2_1.score(x_test_std,y_test))

lr2_0_1.fit(x_train_std,y_train)
print('Train accuracy with L2 and λ=10', lr2_0_1.score(x_train_std,y_train))
print('Test accuracy with L2 and λ=10', lr2_0_1.score(x_test_std,y_test))

L1★★★★★★★★
Trainng accuracy with L1 and λ=0.1 :  1.0
Test accuracy with L1 and λ=0.1 :  0.9814814814814815
Trainng accuracy with L1 and λ=1 :  1.0
Test accuracy with L1 and λ=1 :  1.0
Trainng accuracy with L1 and λ=10 :  0.967741935483871
Test accuracy with L1 and λ=10 :  0.9444444444444444
L2★★★★★★★★
Train accuracy with L2 and λ=0.1 1.0
Test accuracy with L2 and λ=0.1 0.9814814814814815
Train accuracy with L2 and λ=1 1.0
Test accuracy with L2 and λ=1 0.9814814814814815
Train accuracy with L2 and λ=10 1.0
Test accuracy with L2 and λ=10 1.0


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


###L1

In [112]:
print('★★★★★★★★★상수항(계수추정치),y절편★★★★')
#클래스가 3개이기 때문에 intercept도 3개가 나온다
print(lr1_10.intercept_)
print(lr1_1.intercept_)
print(lr1_0_1.intercept_)

print('★★★★★★★★★계수★★★★')
print('★★★★10★★★★')
print(lr1_10.coef_)
print('★★★★1★★★★')
print(lr1_1.coef_)
print('★★★★0.1★★★★')#규제강도가 점점 높아짐
print(lr1_0_1.coef_)

★★★★★★★★★상수항(계수추정치),y절편★★★★
[ 0.32340002  0.56486214 -0.88826216]
[ 0.2874285   0.53768107 -0.82510957]
[ 0.05084043  0.30693171 -0.35777214]
★★★★★★★★★계수★★★★
★★★★10★★★★
[[ 1.2259883   0.          0.18287813 -1.62617846  0.          0.33535173
   0.71668311  0.          0.          0.          0.          0.93226671
   1.59147558]
 [-1.75723741 -0.48814289 -1.45127923  1.06696289 -0.30258213 -0.46467391
   0.73453115  0.44567889  0.15695646 -1.44815482  1.13037738  0.
  -2.00627928]
 [ 0.005879    0.10972899  0.74141446  0.0362277   0.18226499  0.
  -1.97181987 -0.02985296 -0.38740338  1.34789027 -1.2109583  -0.91689666
   0.        ]]
★★★★1★★★★
[[ 0.02748942  0.          0.         -1.17920995  0.          0.
   0.04469769  0.          0.          0.          0.          0.61282629
   0.97972961]
 [-1.57063825 -0.14985598 -0.76518821  0.03542203 -0.06798917  0.
   0.          0.13315451  0.         -1.03089703  0.22306348  0.
  -1.21394086]
 [ 0.          0.          0.          0.    

###L2

In [113]:
print('★★★★★★★★★추정치★★★★')
print(lr2_10.intercept_)
print(lr2_1.intercept_)
print(lr2_0_1.intercept_)

print('★★★★★★★★★계수★★★★')
print('★★★★10★★★★')
print(lr2_10.coef_)
print('★★★★1★★★★')
print(lr2_1.coef_)
print('★★★★0.1★★★★')
print(lr2_0_1.coef_)

★★★★★★★★★추정치★★★★
[ 0.35543266  0.63564187 -0.99107452]
[ 0.28120926  0.60221872 -0.88342798]
[ 0.0683491   0.45677868 -0.52512778]
★★★★★★★★★계수★★★★
★★★★10★★★★
[[ 1.21829247  0.20175807  0.40374148 -1.5253365   0.0474662   0.45174934
   0.78950608 -0.31212787  0.12032044  0.12746052  0.09392905  0.90869296
   1.45662046]
 [-1.53617882 -0.46567644 -1.24892749  1.20666884 -0.30052051 -0.58385178
   0.88848379  0.41272497  0.39700433 -1.29702136  1.13978064  0.09350063
  -1.81143942]
 [ 0.31788636  0.26391837  0.84518601  0.31866766  0.25305431  0.13210244
  -1.67798987 -0.1005971  -0.51732477  1.16956084 -1.23370969 -1.00219359
   0.35481896]]
★★★★1★★★★
[[ 0.75495368  0.06167923  0.23374683 -0.8927082   0.02661043  0.29471545
   0.56016823 -0.20717178  0.13400776  0.12730763  0.10188727  0.61764178
   0.90968482]
 [-0.98654874 -0.32326036 -0.65180321  0.6679768  -0.22927424 -0.20768448
   0.43808631  0.19878757  0.24376048 -0.78046365  0.6369763   0.08551665
  -1.03469523]
 [ 0.23159506  0